# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    sync_code_signing(type: "appstore")

    api_key = app_store_connect_api_key(
      key_id: "6889KV46S3",
      issuer_id: "3c6fa2e8-6b73-4081-a4ab-b9268ffc549a",
      key_filepath: "./AuthKey_6889KV46S3.p8",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )

    increment_build_number(xcodeproj: "Oslyn.xcodeproj")
    build_app(workspace: "Oslyn.xcworkspace", scheme: "Oslyn")
    upload_to_testflight(api_key: api_key)
  end
end